service: expert-ai-api-backend #Replace it using your application name

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  timeout: 30
  stackTags:
    appname: ${self:service.name}
    createdby: serverless #replace it by your email id
    owner: appdev
    approle: creating serverless framework
    environment: ${self:provider.stage}

# plugin to run it locally
plugins:
  - serverless-offline
  - serverless-webpack

# lambda functions
functions:
  # sample hello world api
  helloWorld:
    # path of the file where the function is written
    handler: src/api/handler.helloWorld
    events:
      - http:
         # http request path
         path: /hello
         method: GET