service: expert-ai-api-backend #Replace it using your application name

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  timeout: 30
  stackTags:
    appname: ${self:service.name}
    createdby: serverless #replace it by your email id
    owner: appdev
    approle: creating serverless framework
    environment: ${self:provider.stage}
  environment:
    HOST_NAME: search-expertai-jlyvjjfqyaq3tph5tv7f47v564.us-east-1.es.amazonaws.com
    USERNAME: admin
    PASSWORD: Qwerty@1

# plugin to run it locally
plugins:
  - serverless-offline
  - serverless-webpack

# lambda functions
functions:

  getToken:
    handler: src/api/expertai.getToken
    events:
      - http:
         # http request path
         path: /token
         method: POST

  hateSpeech:
    handler: src/api/expertai.hateSpeech
    events:
      - http:
         # http request path
         path: /hate-speech
         method: POST

  emotionalTraits:
    handler: src/api/expertai.emotionalTraits
    events:
      - http:
          # http request path
          path: /emotional-traits
          method: POST

  behavioralTraits:
    handler: src/api/expertai.behavioralTraits
    events:
      - http:
          # http request path
          path: /behavioral-traits
          method: POST
